virtual gigacube + fsck setup
rubenhoenle/gigacube pull request #6
Opened 2024-04-30 19:14 UTC by Golo300

added virtual gigacube for simulating gigacube with pygame. Not all features of the real hardware are supported. Added multiplayer and fasck animation.

2024-04-30 19:15 UTC, Golo300 commented
works

2024-05-07 19:33 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/__init__.py
> +from .gigacube import Gigacube
what is "faradaycage"? Could we have some words in the documentation about that? :smile:

2024-05-07 19:34 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/gigacube.py
> +        #thread.daemon = True                            # Daemonize thread
remove commented code

2024-05-07 19:34 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/gigacube.py
> +                    # virtuell input
```suggestion
                    # virtual input
```

2024-05-07 19:34 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/gigacube.py
> +            #self.setColor(0, [(random.randint(0, 256), random.randint(0, 256), random.randint(0, 256)) if i < colorSize1 else None for i in range(self.LED_MATRIX_SIZE * self.LED_MATRIX_SIZE * 2)])
remove commented code

2024-05-07 19:35 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +            # Put any initialization here.
what's that comment for? Copy-pasta accident?

2024-05-07 19:35 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +        cube = Gigacube()
self.cube or cube?

2024-05-07 19:37 UTC, rubenhoenle commented on faradaycage/neopixelLibary/neopixel/__pycache__/hypervisor.cpython-311.pyc
gitignore `__pycache__`

2024-05-07 19:37 UTC, rubenhoenle commented on flake.nix
> +          #AMPY_PORT = "/dev/ttyACM0";
why is that commented out?

2024-05-07 19:38 UTC, rubenhoenle commented on lib/displaycontroller.py
> +#import webserver
remove commented code

2024-05-07 19:38 UTC, rubenhoenle commented on lib/nunchuck.py
> +if virtuell:
```suggestion
if virtual:

```

2024-05-07 19:38 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:38 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:38 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:39 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:39 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:39 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:39 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:39 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:40 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:40 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:40 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:40 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:40 UTC, rubenhoenle commented on lib/nunchuck.py
> +        if virtuell:
```suggestion
        if virtual:

```

2024-05-07 19:41 UTC, rubenhoenle commented on main.py
> +        if still_alive == 0:
use else if here

2024-05-07 19:41 UTC, rubenhoenle commented on main.py
>      #        a[0], a[1], a[2],
remove commented code

2024-05-07 19:42 UTC, rubenhoenle commented on main.py
>  #_thread.start_new_thread(blink, gamelogic)
remove commented code

2024-05-07 19:42 UTC, rubenhoenle commented on main.py
>      #webserver.webserver_hook(gamelogic)
remove commented code

2024-05-07 19:42 UTC, rubenhoenle requested changes
see above

2024-05-14 15:54 UTC, Golo300 commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +            # Put any initialization here.
Yes copy pasta

2024-05-14 15:55 UTC, Golo300 commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +        import threading
I remember it being on purpose but I don't remember why... let me think

2024-07-23 18:20 UTC, Golo300 commented on faradaycage/gigacubeLibary/gigacube/__init__.py
> +from .gigacube import Gigacube
wrote README

2024-07-23 18:21 UTC, Golo300 commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +        import threading
it is important

2024-07-24 22:10 UTC, rubenhoenle approved these changes

2024-07-24 22:11 UTC, rubenhoenle commented on faradaycage/gigacubeLibary/gigacube/hypervisor.py
> +        import threading
Sounds like pfusch but well it works...

2024-07-24 22:12 UTC, merged